[tox]
envlist = py310,py311,format,lint
skipsdist = True

[testenv]
deps = -r requirements.txt
commands = pytest {posargs}

[testenv:format]
deps = 
    black
    isort
commands =
    black src tests
    isort src tests

[testenv:lint]
deps =
    flake8
    pylint
commands =
    flake8 src tests
    pylint src tests
