[tox]
envlist = py310,py311,format,lint
skipsdist = True

[testenv]
deps = -r requirements.txt
commands = pytest {posargs}

[testenv:format]
deps = 
    black
    isort
    autoflake
commands =
    autoflake --remove-all-unused-imports --remove-unused-variables --in-place --recursive src tests app.py
    black src tests app.py
    isort src tests app.py

[testenv:lint]
deps =
    flake8
    pylint
commands =
    flake8 src tests
    pylint src tests
