name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main 

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # To fetch all history for LFS if needed

      - name: Push to HF Space
        run: |
          git clone https://huggingface.co/spaces/mukiibi/AskXeno hf_space
          rsync -av --delete ./ hf_space/
          cd hf_space
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "Sync from GitHub" || echo "No changes to commit"
          git push https://mukiibi:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/mukiibi/AskXeno main
